name: Build, Test, and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://testuser:testpassword@localhost:5432/testdb"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Build and Run Docker Compose
        run: docker compose up -d --build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install All Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Wait for services to be ready
        run: |
          echo "Waiting for the web server to be ready..."
          timeout=60
          while ! curl -s --fail http://localhost:8000/; do
            sleep 5
            timeout=$((timeout-5))
            if [ $timeout -le 0 ]; then
              echo "Timed out waiting for server."
              docker compose logs
              exit 1
            fi
          done
          echo "Server is ready!"

      - name: Run Playwright E2E tests
        run: pytest e2e_tests/
        
      - name: Run Integration and Unit tests
        run: docker compose exec app pytest tests/

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/login-registration:latest